### ISSUE TITLE
Agent.add_submodule: error persists after trying to add a component

### ISSUE THREAD

**Issue by rondelion** [wbap/V1#1]
Component を Agent に足そうとするとエラーになります（仕様）が、
その後で通常の Module を足しても同じエラーが出てしまいます。

ログ：

> > > import numpy as np
> > > import brica1
> > > CompA = brica1.ConstantComponent()
> > > ModA = brica1.Module()
> > > ModA.add_component("CompA", CompA)
> > > s = brica1.VirtualTimeSyncScheduler()
> > > agent = brica1.Agent(s)
> > > agent.add_submodule("ModA", ModA)
> > > agent.add_submodule("ModA", ModA)　← add_submoduleを２度呼んでも大丈夫
> > > agent.add_submodule("CompA", CompA)　← Component を Agent に足そうとするとエラー
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "brica1/module.py", line 232, in add_submodule
> > >     self.update_scheduler()
> > >   File "brica1/module.py", line 217, in update_scheduler
> > >     self.scheduler.update(self)
> > >   File "brica1/scheduler.py", line 70, in update
> > >     self.components = ca.get_all_components()
> > >   File "brica1/module.py", line 156, in get_all_components
> > >     for submodule in self.get_all_submodules():
> > >   File "brica1/module.py", line 95, in get_all_submodules
> > >     array.extend(submodule.get_all_submodules())
> > > AttributeError: 'ConstantComponent' object has no attribute 'get_all_submodules'
> > > agent.add_submodule("ModA", ModA)　← 通常の Module を足しても同じエラー
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "brica1/module.py", line 232, in add_submodule
> > >     self.update_scheduler()
> > >   File "brica1/module.py", line 217, in update_scheduler
> > >     self.scheduler.update(self)
> > >   File "brica1/scheduler.py", line 70, in update
> > >     self.components = ca.get_all_components()
> > >   File "brica1/module.py", line 156, in get_all_components
> > >     for submodule in self.get_all_submodules():
> > >   File "brica1/module.py", line 95, in get_all_submodules
> > >     array.extend(submodule.get_all_submodules())
> > > AttributeError: 'ConstantComponent' object has no attribute 'get_all_submodules'

**Comment by ktnyt** [comment]
`agent.add_submodule("CompA", CompA)　← Component を Agent に足そうとするとエラー`
ここでadd_submoduleの引数にComponentを渡しているのでComponentのルックアップの際にComponentをModuleとして解釈しようとしていますね。
`agent.remove_submodule("CompA")`
を実行すれば問題なく動作するかと思いますがどうでしょうか。

**Comment by rondelion** [comment]
ここで問題にしたのは、あるメソッドのエラーが別のメソッドのエラーを引き起こしてしまうことでした。
add_submodule() で Component を指定した場合、add_component() で Module を指定した場合にはメソッド内で isinstance 判定を行って例外を投げるなどのエラー処理を行えないでしょうか。

**Comment by ktnyt** [comment]
間違った型を引数に与えた場合にAssertionErrorをraiseするように更新しました。いかがでしょうか。

**Comment by rondelion** [comment]
pull してみたのですが、module.py が変更されていますね。agent クラスでの引数チェックをお願いしたいです。

**Comment by rondelion** [comment]
修正を確認しました。
